/**
 * # RegionList.js
 *
 */

exports.Regions = [
    {
        uniquecode: "110100", shortname: "北京1", firstchar: "B",
        sub: [
            { uniquecode: "450321", shortname: "阳朔", firstchar: "Y" },
            { uniquecode: "330382", shortname: "乐清", firstchar: "Y" },
            { uniquecode: "441881", shortname: "英德", firstchar: "Y" },
            { uniquecode: "410329", shortname: "伊川", firstchar: "Y" },
            { uniquecode: "321081", shortname: "仪征", firstchar: "Y" },
            { uniquecode: "410381", shortname: "偃师", firstchar: "Y" },
            { uniquecode: "321182", shortname: "扬中", firstchar: "Y" },
            { uniquecode: "411481", shortname: "永城", firstchar: "Y" },
            { uniquecode: "140881", shortname: "永济", firstchar: "Y" },
            { uniquecode: "371482", shortname: "禹城", firstchar: "Y" },
            { uniquecode: "411081", shortname: "禹州", firstchar: "Y" },
            { uniquecode: "654002", shortname: "伊宁", firstchar: "Y" },
            { uniquecode: "420684", shortname: "宜城", firstchar: "Y" },
            { uniquecode: "140981", shortname: "原平", firstchar: "Y" },
            { uniquecode: "420981", shortname: "应城", firstchar: "Y" },
            { uniquecode: "420581", shortname: "宜都", firstchar: "Y" },
            { uniquecode: "430981", shortname: "沅江", firstchar: "Y" },
            { uniquecode: "331021", shortname: "玉环", firstchar: "Y" },
            { uniquecode: "500118", shortname: "永川", firstchar: "Y" },
            { uniquecode: "130429", shortname: "永年", firstchar: "Y" },
            { uniquecode: "140522", shortname: "阳城", firstchar: "Y" },
            { uniquecode: "500235", shortname: "云阳", firstchar: "Y" },
            { uniquecode: "410422", shortname: "叶县", firstchar: "Y" },
            { uniquecode: "130633", shortname: "易县", firstchar: "Y" },
            { uniquecode: "410327", shortname: "宜阳", firstchar: "Y" },
            { uniquecode: "610114", shortname: "阎良", firstchar: "Y" },
            { uniquecode: "410725", shortname: "原阳", firstchar: "Y" },
            { uniquecode: "411425", shortname: "虞城", firstchar: "Y" },
            { uniquecode: "361123", shortname: "玉山", firstchar: "Y" },
            { uniquecode: "371521", shortname: "阳谷", firstchar: "Y" },
            { uniquecode: "371725", shortname: "郓城", firstchar: "Y" },
            { uniquecode: "150627", shortname: "伊金霍洛旗", firstchar: "Y" },
            { uniquecode: "371323", shortname: "沂水", firstchar: "Y" },
            { uniquecode: "371321", shortname: "沂南", firstchar: "Y" },
            { uniquecode: "360731", shortname: "于都", firstchar: "Y" },
            { uniquecode: "410100", shortname: "郑州", firstchar: "Z" },
            { uniquecode: "321100", shortname: "镇江", firstchar: "Z" },
            { uniquecode: "442000", shortname: "中山", firstchar: "Z" },
            { uniquecode: "370300", shortname: "淄博", firstchar: "Z" },
            { uniquecode: "440400", shortname: "珠海", firstchar: "Z" },
            { uniquecode: "520300", shortname: "遵义", firstchar: "Z" },
            { uniquecode: "430200", shortname: "株洲", firstchar: "Z" },
            { uniquecode: "130700", shortname: "张家口", firstchar: "Z" },
            { uniquecode: "330900", shortname: "舟山", firstchar: "Z" },
            { uniquecode: "350600", shortname: "漳州", firstchar: "Z" },
            { uniquecode: "370400", shortname: "枣庄", firstchar: "Z" },
            { uniquecode: "411600", shortname: "周口", firstchar: "Z" },
            { uniquecode: "411700", shortname: "驻马店", firstchar: "Z" },
            { uniquecode: "430800", shortname: "张家界", firstchar: "Z" },
            { uniquecode: "440800", shortname: "湛江", firstchar: "Z" },
            { uniquecode: "441200", shortname: "肇庆", firstchar: "Z" },
            { uniquecode: "510300", shortname: "自贡", firstchar: "Z" },
            { uniquecode: "512000", shortname: "资阳", firstchar: "Z" },
            { uniquecode: "530600", shortname: "昭通", firstchar: "Z" },
            { uniquecode: "620700", shortname: "张掖", firstchar: "Z" },
            { uniquecode: "640500", shortname: "中卫", firstchar: "Z" },
            { uniquecode: "320582", shortname: "张家港", firstchar: "Z" },
            { uniquecode: "130681", shortname: "涿州", firstchar: "Z" },
            { uniquecode: "370181", shortname: "章丘", firstchar: "Z" },
            { uniquecode: "330681", shortname: "诸暨", firstchar: "Z" },
            { uniquecode: "440118", shortname: "增城", firstchar: "Z" },
            { uniquecode: "420683", shortname: "枣阳", firstchar: "Z" },
            { uniquecode: "371626", shortname: "邹平", firstchar: "Z" },
            { uniquecode: "370782", shortname: "诸城", firstchar: "Z" },
            { uniquecode: "210283", shortname: "庄河", firstchar: "Z" },
            { uniquecode: "370685", shortname: "招远", firstchar: "Z" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京2", firstchar: "B",
        sub: [
            { uniquecode: "450321", shortname: "阳朔", firstchar: "Y" },
            { uniquecode: "330382", shortname: "乐清", firstchar: "Y" },
            { uniquecode: "441881", shortname: "英德", firstchar: "Y" },
            { uniquecode: "410329", shortname: "伊川", firstchar: "Y" },
            { uniquecode: "321081", shortname: "仪征", firstchar: "Y" },
            { uniquecode: "410381", shortname: "偃师", firstchar: "Y" },
            { uniquecode: "321182", shortname: "扬中", firstchar: "Y" },
            { uniquecode: "411481", shortname: "永城", firstchar: "Y" },
            { uniquecode: "140881", shortname: "永济", firstchar: "Y" },
            { uniquecode: "371482", shortname: "禹城", firstchar: "Y" },
            { uniquecode: "411081", shortname: "禹州", firstchar: "Y" },
            { uniquecode: "654002", shortname: "伊宁", firstchar: "Y" },
            { uniquecode: "420684", shortname: "宜城", firstchar: "Y" },
            { uniquecode: "140981", shortname: "原平", firstchar: "Y" },
            { uniquecode: "420981", shortname: "应城", firstchar: "Y" },
            { uniquecode: "420581", shortname: "宜都", firstchar: "Y" },
            { uniquecode: "430981", shortname: "沅江", firstchar: "Y" },
            { uniquecode: "331021", shortname: "玉环", firstchar: "Y" },
            { uniquecode: "500118", shortname: "永川", firstchar: "Y" },
            { uniquecode: "130429", shortname: "永年", firstchar: "Y" },
            { uniquecode: "140522", shortname: "阳城", firstchar: "Y" },
            { uniquecode: "500235", shortname: "云阳", firstchar: "Y" },
            { uniquecode: "410422", shortname: "叶县", firstchar: "Y" },
            { uniquecode: "130633", shortname: "易县", firstchar: "Y" },
            { uniquecode: "410327", shortname: "宜阳", firstchar: "Y" },
            { uniquecode: "610114", shortname: "阎良", firstchar: "Y" },
            { uniquecode: "410725", shortname: "原阳", firstchar: "Y" },
            { uniquecode: "411425", shortname: "虞城", firstchar: "Y" },
            { uniquecode: "361123", shortname: "玉山", firstchar: "Y" },
            { uniquecode: "371521", shortname: "阳谷", firstchar: "Y" },
            { uniquecode: "371725", shortname: "郓城", firstchar: "Y" },
            { uniquecode: "150627", shortname: "伊金霍洛旗", firstchar: "Y" },
            { uniquecode: "371323", shortname: "沂水", firstchar: "Y" },
            { uniquecode: "371321", shortname: "沂南", firstchar: "Y" },
            { uniquecode: "360731", shortname: "于都", firstchar: "Y" },
            { uniquecode: "410100", shortname: "郑州", firstchar: "Z" },
            { uniquecode: "321100", shortname: "镇江", firstchar: "Z" },
            { uniquecode: "442000", shortname: "中山", firstchar: "Z" },
            { uniquecode: "370300", shortname: "淄博", firstchar: "Z" },
            { uniquecode: "440400", shortname: "珠海", firstchar: "Z" },
            { uniquecode: "520300", shortname: "遵义", firstchar: "Z" },
            { uniquecode: "430200", shortname: "株洲", firstchar: "Z" },
            { uniquecode: "130700", shortname: "张家口", firstchar: "Z" },
            { uniquecode: "330900", shortname: "舟山", firstchar: "Z" },
            { uniquecode: "350600", shortname: "漳州", firstchar: "Z" },
            { uniquecode: "370400", shortname: "枣庄", firstchar: "Z" },
            { uniquecode: "411600", shortname: "周口", firstchar: "Z" },
            { uniquecode: "411700", shortname: "驻马店", firstchar: "Z" },
            { uniquecode: "430800", shortname: "张家界", firstchar: "Z" },
            { uniquecode: "440800", shortname: "湛江", firstchar: "Z" },
            { uniquecode: "441200", shortname: "肇庆", firstchar: "Z" },
            { uniquecode: "510300", shortname: "自贡", firstchar: "Z" },
            { uniquecode: "512000", shortname: "资阳", firstchar: "Z" },
            { uniquecode: "530600", shortname: "昭通", firstchar: "Z" },
            { uniquecode: "620700", shortname: "张掖", firstchar: "Z" },
            { uniquecode: "640500", shortname: "中卫", firstchar: "Z" },
            { uniquecode: "320582", shortname: "张家港", firstchar: "Z" },
            { uniquecode: "130681", shortname: "涿州", firstchar: "Z" },
            { uniquecode: "370181", shortname: "章丘", firstchar: "Z" },
            { uniquecode: "330681", shortname: "诸暨", firstchar: "Z" },
            { uniquecode: "440118", shortname: "增城", firstchar: "Z" },
            { uniquecode: "420683", shortname: "枣阳", firstchar: "Z" },
            { uniquecode: "371626", shortname: "邹平", firstchar: "Z" },
            { uniquecode: "370782", shortname: "诸城", firstchar: "Z" },
            { uniquecode: "210283", shortname: "庄河", firstchar: "Z" },
            { uniquecode: "370685", shortname: "招远", firstchar: "Z" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京3", firstchar: "B",
        sub: [
            { uniquecode: "450321", shortname: "阳朔", firstchar: "Y" },
            { uniquecode: "330382", shortname: "乐清", firstchar: "Y" },
            { uniquecode: "441881", shortname: "英德", firstchar: "Y" },
            { uniquecode: "410329", shortname: "伊川", firstchar: "Y" },
            { uniquecode: "321081", shortname: "仪征", firstchar: "Y" },
            { uniquecode: "410381", shortname: "偃师", firstchar: "Y" },
            { uniquecode: "321182", shortname: "扬中", firstchar: "Y" },
            { uniquecode: "411481", shortname: "永城", firstchar: "Y" },
            { uniquecode: "140881", shortname: "永济", firstchar: "Y" },
            { uniquecode: "371482", shortname: "禹城", firstchar: "Y" },
            { uniquecode: "411081", shortname: "禹州", firstchar: "Y" },
            { uniquecode: "654002", shortname: "伊宁", firstchar: "Y" },
            { uniquecode: "420684", shortname: "宜城", firstchar: "Y" },
            { uniquecode: "140981", shortname: "原平", firstchar: "Y" },
            { uniquecode: "420981", shortname: "应城", firstchar: "Y" },
            { uniquecode: "420581", shortname: "宜都", firstchar: "Y" },
            { uniquecode: "430981", shortname: "沅江", firstchar: "Y" },
            { uniquecode: "331021", shortname: "玉环", firstchar: "Y" },
            { uniquecode: "500118", shortname: "永川", firstchar: "Y" },
            { uniquecode: "130429", shortname: "永年", firstchar: "Y" },
            { uniquecode: "140522", shortname: "阳城", firstchar: "Y" },
            { uniquecode: "500235", shortname: "云阳", firstchar: "Y" },
            { uniquecode: "410422", shortname: "叶县", firstchar: "Y" },
            { uniquecode: "130633", shortname: "易县", firstchar: "Y" },
            { uniquecode: "410327", shortname: "宜阳", firstchar: "Y" },
            { uniquecode: "610114", shortname: "阎良", firstchar: "Y" },
            { uniquecode: "410725", shortname: "原阳", firstchar: "Y" },
            { uniquecode: "411425", shortname: "虞城", firstchar: "Y" },
            { uniquecode: "361123", shortname: "玉山", firstchar: "Y" },
            { uniquecode: "371521", shortname: "阳谷", firstchar: "Y" },
            { uniquecode: "371725", shortname: "郓城", firstchar: "Y" },
            { uniquecode: "150627", shortname: "伊金霍洛旗", firstchar: "Y" },
            { uniquecode: "371323", shortname: "沂水", firstchar: "Y" },
            { uniquecode: "371321", shortname: "沂南", firstchar: "Y" },
            { uniquecode: "360731", shortname: "于都", firstchar: "Y" },
            { uniquecode: "410100", shortname: "郑州", firstchar: "Z" },
            { uniquecode: "321100", shortname: "镇江", firstchar: "Z" },
            { uniquecode: "442000", shortname: "中山", firstchar: "Z" },
            { uniquecode: "370300", shortname: "淄博", firstchar: "Z" },
            { uniquecode: "440400", shortname: "珠海", firstchar: "Z" },
            { uniquecode: "520300", shortname: "遵义", firstchar: "Z" },
            { uniquecode: "430200", shortname: "株洲", firstchar: "Z" },
            { uniquecode: "130700", shortname: "张家口", firstchar: "Z" },
            { uniquecode: "330900", shortname: "舟山", firstchar: "Z" },
            { uniquecode: "350600", shortname: "漳州", firstchar: "Z" },
            { uniquecode: "370400", shortname: "枣庄", firstchar: "Z" },
            { uniquecode: "411600", shortname: "周口", firstchar: "Z" },
            { uniquecode: "411700", shortname: "驻马店", firstchar: "Z" },
            { uniquecode: "430800", shortname: "张家界", firstchar: "Z" },
            { uniquecode: "440800", shortname: "湛江", firstchar: "Z" },
            { uniquecode: "441200", shortname: "肇庆", firstchar: "Z" },
            { uniquecode: "510300", shortname: "自贡", firstchar: "Z" },
            { uniquecode: "512000", shortname: "资阳", firstchar: "Z" },
            { uniquecode: "530600", shortname: "昭通", firstchar: "Z" },
            { uniquecode: "620700", shortname: "张掖", firstchar: "Z" },
            { uniquecode: "640500", shortname: "中卫", firstchar: "Z" },
            { uniquecode: "320582", shortname: "张家港", firstchar: "Z" },
            { uniquecode: "130681", shortname: "涿州", firstchar: "Z" },
            { uniquecode: "370181", shortname: "章丘", firstchar: "Z" },
            { uniquecode: "330681", shortname: "诸暨", firstchar: "Z" },
            { uniquecode: "440118", shortname: "增城", firstchar: "Z" },
            { uniquecode: "420683", shortname: "枣阳", firstchar: "Z" },
            { uniquecode: "371626", shortname: "邹平", firstchar: "Z" },
            { uniquecode: "370782", shortname: "诸城", firstchar: "Z" },
            { uniquecode: "210283", shortname: "庄河", firstchar: "Z" },
            { uniquecode: "370685", shortname: "招远", firstchar: "Z" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京4", firstchar: "B",
        sub: [
            { uniquecode: "120100", shortname: "天津", firstchar: "T" },
            { uniquecode: "420100", shortname: "武汉", firstchar: "W" },
            { uniquecode: "500100", shortname: "重庆", firstchar: "C" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京5", firstchar: "B",
        sub: [
            { uniquecode: "120100", shortname: "天津", firstchar: "T" },
            { uniquecode: "420100", shortname: "武汉", firstchar: "W" },
            { uniquecode: "500100", shortname: "重庆", firstchar: "C" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京6", firstchar: "B",
        sub: [
            { uniquecode: "120100", shortname: "天津", firstchar: "T" },
            { uniquecode: "420100", shortname: "武汉", firstchar: "W" },
            { uniquecode: "500100", shortname: "重庆", firstchar: "C" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京7", firstchar: "B",
        sub: [
            { uniquecode: "120100", shortname: "天津", firstchar: "T" },
            { uniquecode: "420100", shortname: "武汉", firstchar: "W" },
            { uniquecode: "500100", shortname: "重庆", firstchar: "C" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京8", firstchar: "B",
        sub: [
            { uniquecode: "120100", shortname: "天津", firstchar: "T" },
            { uniquecode: "420100", shortname: "武汉", firstchar: "W" },
            { uniquecode: "500100", shortname: "重庆", firstchar: "C" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京9", firstchar: "B",
        sub: [
            { uniquecode: "120100", shortname: "天津", firstchar: "T" },
            { uniquecode: "420100", shortname: "武汉", firstchar: "W" },
            { uniquecode: "500100", shortname: "重庆", firstchar: "C" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京10", firstchar: "B",
        sub: [
            { uniquecode: "120100", shortname: "天津", firstchar: "T" },
            { uniquecode: "420100", shortname: "武汉", firstchar: "W" },
            { uniquecode: "500100", shortname: "重庆", firstchar: "C" }
        ]
    },
    {
        uniquecode: "110100", shortname: "北京", firstchar: "B",
        sub: [
            { uniquecode: "210283", shortname: "庄河", firstchar: "Z" },
            { uniquecode: "370685", shortname: "招远", firstchar: "Z" },
            { uniquecode: "130281", shortname: "遵化", firstchar: "Z" },
            { uniquecode: "420881", shortname: "钟祥", firstchar: "Z" },
            { uniquecode: "420583", shortname: "枝江", firstchar: "Z" },
            { uniquecode: "350623", shortname: "漳浦", firstchar: "Z" },
            { uniquecode: "360982", shortname: "樟树", firstchar: "Z" },
            { uniquecode: "130123", shortname: "正定", firstchar: "Z" },
            { uniquecode: "410122", shortname: "中牟", firstchar: "Z" },
            { uniquecode: "370883", shortname: "邹城", firstchar: "Z" },
            { uniquecode: "130133", shortname: "赵县", firstchar: "Z" },
            { uniquecode: "411424", shortname: "柘城", firstchar: "Z" },
            { uniquecode: "150622", shortname: "准格尔旗", firstchar: "Z" }
        ]
    }

];
